### ISSUE TITLE
http GET API request recall salvo (preset)

### ISSUE THREAD

**Issue by Federico-Catelotti** [olzzon/ndi-controller#3]
Formidable! I really like it a lot!

Is tehre a way to recall a preset froma an http GET API request?

**Comment by olzzon** [comment]
Hi Frederico,

Thanks a lot :) 

I've just added the feature to the REST API: 
(will be included in next release)
### Recall a Salvo (preset)
```
POST http://localhost:5901/recall/?preset=2
```

Best regards
Kasper

**Comment by olzzon** [comment]
It in the new 1.2.0 release :)
