### ISSUE TITLE
On PC, seems I need to exit app to "save changes"

### ISSUE THREAD

**Issue by leotbGit** [olzzon/ndi-controller#7]
Even after clicking _Update_ on say the source dialogue and then _Update_ on the main page, it still does not save changes till I shut down and re start the app. **V1.3.0**

Nice work by the way!

**Comment by olzzon** [comment]
thanks for reporting, we will fix this for the next release :)

**Comment by olzzon** [comment]
The "update" button has now been changed so "Save & Restart" and NDI Controller will restart after saving.
